!+
! Fortran side of the Bmad / C++ structure interface.
!
! This file is generated by the Bmad/C++ interface code generation.
! The code generation files can be found in cpp_bmad_interface.
!
! DO NOT EDIT THIS FILE DIRECTLY! 
!-

module bmad_cpp_convert_mod

use fortran_cpp_utils
use bmad_struct
use tao_struct

use, intrinsic :: iso_c_binding

! ${interfaces}

contains

!-----------------------------------------------------------------------------

subroutine lat_struct_to_f2_finalize_ele(lat, branch, ele)

  use bmad_struct, only: lat_struct, branch_struct, ele_struct

type (lat_struct), target :: lat
type (branch_struct), pointer :: branch
type (ele_struct), pointer :: ele, lord

  ! ele_struct%branch
 
  ele%branch => branch
  if (.not. associated(ele%lord)) then
    return
  endif

  ! ele_struct%lord is just a reference
  if (ele%lord%ix_branch >= lbound(lat%branch, 1) .and. ele%lord%ix_branch <= ubound(lat%branch, 1)) then
    if (ele%lord%ix_ele >= lbound(lat%branch(ele%lord%ix_branch)%ele, 1) .and. ele%lord%ix_ele <= ubound(lat%branch(ele%lord%ix_branch)%ele, 1)) then
      ele%lord => lat%branch(ele%lord%ix_branch)%ele(ele%lord%ix_ele)
    endif
  endif

end subroutine

subroutine lat_struct_to_f2_finalize(lat)

  use bmad_struct, only: lat_struct, branch_struct, ele_struct

implicit none

type (lat_struct), target :: lat
type (branch_struct), pointer :: branch
! type (lat_ele_loc_struct), pointer :: loc
type (ele_struct), pointer :: ele

integer ib, ie

if (.not. allocated(lat%branch)) return

if (lat%use_name == 'TEST-LATTICE-FROM-TEST-SUITE') then
  return
endif

do ib = 0, ubound(lat%branch, 1)
  branch => lat%branch(ib)
  branch%lat => lat
  if (associated(branch)) then
    do ie = 0, min(branch%n_ele_max, ubound(branch%ele, 1))
      ele => branch%ele(ie)
      call lat_struct_to_f2_finalize_ele(lat, branch, ele)
    enddo
  endif
enddo
lat%ele => lat%branch(0)%ele

end subroutine lat_struct_to_f2_finalize

! ${contains}

end module bmad_cpp_convert_mod
