"""
Script to create:

* C++ classes for Fortran structures
* Translator between Fortran structure and C++ class
* Routines to check for equality between instances of a given Fortran structure.
* Routines to check for equality between instances of a given C++ class
* Program to check the Fortran / C++ translator

Note: The corresponding C++ class component for a pointer or allocatable Fortran
scalar struct component is an array whose length is zero if the Fortran component
is nullified and whose length is 1 otherwise.
"""

from __future__ import annotations

import argparse
import logging
import logging.handlers
import pathlib

from codegen.proxy import get_proxy_classes

from .arg import Argument, CodegenStructure
from .context import CodegenConfig, ConfigContext, UpstreamInfo, config_context
from .docs import generate_docs
from .enums import get_enum_code, parse_all_enums
from .paths import (
    CODEGEN_ROOT,
    CPPBMAD_INCLUDE,
    CPPBMAD_SRC,
    PYBMAD_INCLUDE,
    PYBMAD_ROOT,
    PYBMAD_SRC,
)
from .py import generate_pybmad
from .routines import generate_routines, load_routines
from .structs import ParsedStructure, load_bmad_parser_structures
from .util import write_contents_if_differs

logger = logging.getLogger(__name__)

DEBUG = False  # Change to True to enable more verbose printout


def match_structure_definition(
    parsed_structures: list[ParsedStructure],
    struct: CodegenStructure,
    params: CodegenConfig,
):
    for fstruct in parsed_structures:
        if struct.f_name.lower() == fstruct.name.lower():
            break
    else:
        raise RuntimeError(f"Structure not found: {struct.f_name!r}")

    struct.f_name = fstruct.name
    struct.arg = [
        Argument.from_fstruct(fstruct, member, params=params) for member in fstruct.members.values()
    ]
    struct.module = fstruct.module
    struct.parsed = fstruct


def check_missing(params: CodegenConfig, structs: list[CodegenStructure]) -> dict[str, dict[str, str]]:
    struct_names = {struct.f_name.lower() for struct in structs}

    missing_by_struct = {}
    for struct in structs:
        to_remove = []
        for idx, fld in enumerate(list(struct.arg)):
            if fld.type != "type" or fld.kind in params.structs_defined_externally:
                continue

            if fld.kind.lower() not in struct_names:
                logger.warning(
                    f"Missing definition for struct '{fld.kind}' which is used in '{struct.f_name}'"
                )
                missing_by_struct.setdefault(struct.f_name, {})
                missing_by_struct[struct.f_name][fld.f_name] = fld.kind

                to_remove.append(idx)
        for remove in sorted(to_remove, reverse=True):
            struct.arg.pop(remove)

    return missing_by_struct


def filter_structs(
    structs: list[CodegenStructure], allowed_modules: set[str], ignored_modules: set[str]
) -> list[CodegenStructure]:
    return [
        struct
        for struct in structs
        if struct.module in allowed_modules or struct.module not in ignored_modules
    ]


# def get_to_json_source(struct: CodegenStructure) -> list[str]:
#     args = [arg for arg in struct.args_to_convert if arg.is_component and arg.member is not None]
#
#     name_to_value = {arg.c_name: f"obj.{arg.c_name}" for arg in args}
#     # if struct.cpp_class == "CPP_ele":
#     #     name_to_value.pop("lord")
#     #     fixup_lines = [
#     #         "if (obj.lord.has_value()) {",
#     #         '    j["lord"] = json{*obj.lord.value()};',
#     #         "}",
#     #     ]
#     # else:
#     fixup_lines = []
#
#     members = ", ".join("{" + f'"{name}", {value}' + "}" for name, value in name_to_value.items())
#
#     return [
#         f"void to_json(json &j, const {struct.cpp_class} &obj) {{",
#         f"j = json {{ {members} }};",
#         *fixup_lines,
#         "}",
#         f"""
#         ostream &operator<<(ostream &os, const {struct.cpp_class} &obj) {{
#           json j;
#           to_json(j, obj);
#           std::string str = nlohmann::to_string(j);
#           os << str;
#           return os;
#         }}
#         """,
#     ]
#
#
# def write_cpp_json_source(file, structs: list[CodegenStructure]) -> None:
#     """Write C++ JSON serialization code."""
#     header_template = string.Template(
#         textwrap.dedent(
#             """\
#             //+
#             // C++ JSON helpers for Bmad / C++ structure interface.
#             //
#             // This file is generated as part of the Bmad/C++ interface code generation.
#             // The code generation files can be found in cpp_bmad_interface.
#             //
#             // DO NOT EDIT THIS FILE DIRECTLY!
#             //-
#
#             #include <iostream>
#             #include <memory>
#             #include <optional>
#
#             #include "bmad/convert.h"
#             #include "json.hpp"
#             ${include_headers}
#
#             using namespace Bmad;
#             using std::ostream;
#             using std::size_t;
#             using json = nlohmann::json;
#
#             namespace std {
#             template<typename T>
#             void to_json(json& j, const complex<T>& d) {
#                 j = {d.real(), d.imag()};
#             }
#             void from_json(const json& j, Complex &d) {
#                 d.real(j.at(0).get<double>());
#                 d.imag(j.at(1).get<double>());
#             }
#             } // namespace: std
#
#             namespace Bmad {
#             //--------------------------------------------------------------------
#             ${json_helpers}
#             //--------------------------------------------------------------------
#             } // namespace Bmad
#             """
#         )
#     )
#
#     include_headers = "\n".join(params.include_header_files)
#     json_helpers = "\n".join("\n".join(get_to_json_source(struct)) for struct in structs)
#     file.write(header_template.substitute(include_headers=include_headers, json_helpers=json_helpers))


def get_structure_definitions(
    params: CodegenConfig,
    parsed_structures: list[ParsedStructure],
) -> list[CodegenStructure]:
    structs: list[CodegenStructure] = []

    for name in params.struct_list:
        struct = CodegenStructure(name)
        structs.append(struct)
        match_structure_definition(parsed_structures, struct, params)
        struct.arg = [arg for arg in struct.arg if arg.should_translate(struct.f_name, params)]
        if struct.parsed and struct.parsed.filename:
            try:
                project = struct.parsed.filename.parts[1]  # TODO: $ACC_ROOT_DIR/(xyz) is the project
                struct.project = project
            except ValueError:
                struct.project = "unknown"
    return structs


def load_context(
    config_file: pathlib.Path = CODEGEN_ROOT / "default.toml",
    pybmad: bool = True,
) -> ConfigContext:
    logger.debug(f"Config file: {config_file}")
    params = CodegenConfig.from_file(config_file)

    parsed_structs = load_bmad_parser_structures()

    settings_and_routines, routine_structs = load_routines(params, parsed_structs, params)

    # TODO: considering opening up the struct list completely
    # params.struct_list = sorted(set(routine_structs) | set(params.struct_list))
    params.struct_list = params.struct_list
    structs = get_structure_definitions(params, parsed_structs)
    enums = parse_all_enums(params.enum_filenames)

    upstream = UpstreamInfo.from_source_dir(params.source_dir)
    logger.info("Upstream: %s (%s)", upstream.tag, upstream.commit_hash[:12])

    ctx = ConfigContext(
        params=params,
        upstream=upstream,
        codegen_structs=structs,
        parsed_structs=parsed_structs,
        enums=enums,
        missing_struct_attrs=check_missing(params, structs),
        pybmad_files={},
    )
    config_context.set(ctx)
    assert len(ctx.codegen_structs)

    missing_structs = sorted(set(routine_structs) - set(params.struct_list))
    logger.info("Structures not flagged for conversion: %d", len(missing_structs))
    for st in missing_structs:
        logger.debug("Structure not flagged for conversion: %s", st)
    ctx.routines, ctx.routines_by_name, ctx.routine_files = generate_routines(params, settings_and_routines)

    if pybmad:
        ctx.pybmad_files = generate_pybmad(ctx.params, ctx.codegen_structs, ctx.routines_by_name, ctx.enums)

    ctx.docs_files = generate_docs(
        ctx.codegen_structs, ctx.routines_by_name, ctx.enums, ctx.params, ctx.upstream
    )

    return ctx


def generate(
    config_file: pathlib.Path = CODEGEN_ROOT / "default.toml",
    pybmad: bool = True,
    write: bool = True,
):
    ctx = load_context(config_file, pybmad)
    logger.info(f"Number of structs in input list: {len(ctx.codegen_structs)}")
    logger.info(f"Number of structs found:         {len(ctx.parsed_structs)}")

    to_string_header = ctx.cpp_to_string_header
    to_string_code = ctx.cpp_to_string_code
    enum_code = get_enum_code(ctx.enums)
    ctx.proxy_files = get_proxy_classes(ctx.codegen_structs)

    if not write:
        logger.info("File writing disabled.")
        return ctx

    cpp_gen_src = PYBMAD_SRC / "generated"
    hpp_gen_src = PYBMAD_INCLUDE / "pybmad" / "generated"
    existing_files = set(cpp_gen_src.glob("*.cpp")) | set(hpp_gen_src.glob("*.hpp"))
    for fn in existing_files:
        if fn not in ctx.pybmad_files:
            logger.warning(f"Removing stale file from previous generation: {fn}")
            fn.unlink()

    file_and_contents = [
        (PYBMAD_ROOT / "docs" / "source" / "coverage.html", ctx.report_html),
        (CPPBMAD_INCLUDE / "bmad" / "generated" / "enums.hpp", enum_code),
        (CPPBMAD_INCLUDE / "bmad" / "generated" / "to_string.hpp", to_string_header),
        (CPPBMAD_SRC / "generated" / "to_string.cpp", to_string_code),
        *list(ctx.proxy_files.items()),
        *list(ctx.routine_files.items()),
    ]

    if pybmad:
        file_and_contents.extend(list(ctx.pybmad_files.items()))

    file_and_contents.extend(list(ctx.docs_files.items()))

    for fn, contents in file_and_contents:
        write_contents_if_differs(target_path=fn, contents=contents)

    return ctx


def main():
    parser = argparse.ArgumentParser(description="Run the cppbmad code generator.")
    parser.add_argument(
        "--log-level",
        default="INFO",
        choices=["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"],
        help="Set the logging level.",
    )
    parser.add_argument(
        "--config-file",
        type=pathlib.Path,
        default=CODEGEN_ROOT / "default.toml",
        help="Path to the configuration file.",
    )
    parser.add_argument(
        "--no-pybmad",
        action="store_true",
        help="Do not generate pybmad pybind11 bindings",
    )
    parser.add_argument(
        "--no-write",
        action="store_true",
        help="Do not write files",
    )
    parser.add_argument(
        "--debug",
        action="store_true",
        help="Enable debug mode",
    )
    args = parser.parse_args()

    log_file_handler = logging.handlers.RotatingFileHandler("build-log.log", backupCount=5)
    stream_handler = logging.StreamHandler()
    stream_handler.setLevel(args.log_level)
    log_file_handler.setLevel(logging.DEBUG)
    logging.basicConfig(level=args.log_level, handlers=[stream_handler, log_file_handler])
    logging.getLogger("codegen").setLevel(logging.DEBUG)

    return generate(config_file=args.config_file, pybmad=not args.no_pybmad, write=not args.no_write)


if __name__ == "__main__":
    ctx = main()
