name: Conda build & test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-conda:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ubuntu-single-core
            os: ubuntu-latest
            shared: Y
            openmp_mpi: N
            bmad_ref: main
            build_type: release
          - name: macos-single-core
            os: macos-latest
            shared: Y
            openmp_mpi: N
            bmad_ref: main
            build_type: release
          - name: ubuntu-openmp
            os: ubuntu-latest
            shared: Y
            openmp_mpi: Y
            bmad_ref: main
            build_type: release

    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/build-bmad
        with:
          bmad_ref: ${{ matrix.bmad_ref }}
          shared: ${{ matrix.shared }}
          openmp_mpi: ${{ matrix.openmp_mpi }}
          build_type: ${{ matrix.build_type }}
